// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (event_id, endpoint_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
`

type CreateDeliveryParams struct {
	EventID    pgtype.UUID `json:"event_id"`
	EndpointID pgtype.UUID `json:"endpoint_id"`
}

// CreateDelivery
//
//	INSERT INTO deliveries (event_id, endpoint_id, status)
//	VALUES ($1, $2, 'pending')
//	RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery, arg.EventID, arg.EndpointID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptNumber,
		&i.NextAttemptAt,
		&i.LastHttpStatus,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deliveryMetricsSummary = `-- name: DeliveryMetricsSummary :one
SELECT
    COUNT(*) FILTER (WHERE status = 'delivered')     AS delivered,
    COUNT(*) FILTER (WHERE status = 'failed')        AS failed,
    COUNT(*) FILTER (WHERE status = 'dead_lettered') AS dead_lettered,
    COUNT(*) FILTER (WHERE status = 'pending')       AS pending,
    COUNT(*)                                          AS total
FROM deliveries d
JOIN events e ON e.id = d.event_id
WHERE e.project_id = $1
    AND d.created_at >= NOW() - ($2 || ' hours')::interval
`

type DeliveryMetricsSummaryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Column2   *string     `json:"column_2"`
}

type DeliveryMetricsSummaryRow struct {
	Delivered    int64 `json:"delivered"`
	Failed       int64 `json:"failed"`
	DeadLettered int64 `json:"dead_lettered"`
	Pending      int64 `json:"pending"`
	Total        int64 `json:"total"`
}

// DeliveryMetricsSummary
//
//	SELECT
//	    COUNT(*) FILTER (WHERE status = 'delivered')     AS delivered,
//	    COUNT(*) FILTER (WHERE status = 'failed')        AS failed,
//	    COUNT(*) FILTER (WHERE status = 'dead_lettered') AS dead_lettered,
//	    COUNT(*) FILTER (WHERE status = 'pending')       AS pending,
//	    COUNT(*)                                          AS total
//	FROM deliveries d
//	JOIN events e ON e.id = d.event_id
//	WHERE e.project_id = $1
//	    AND d.created_at >= NOW() - ($2 || ' hours')::interval
func (q *Queries) DeliveryMetricsSummary(ctx context.Context, arg DeliveryMetricsSummaryParams) (DeliveryMetricsSummaryRow, error) {
	row := q.db.QueryRow(ctx, deliveryMetricsSummary, arg.ProjectID, arg.Column2)
	var i DeliveryMetricsSummaryRow
	err := row.Scan(
		&i.Delivered,
		&i.Failed,
		&i.DeadLettered,
		&i.Pending,
		&i.Total,
	)
	return i, err
}

const getDeliveryByEventAndEndpoint = `-- name: GetDeliveryByEventAndEndpoint :one
SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries
WHERE event_id = $1 AND endpoint_id = $2
LIMIT 1
`

type GetDeliveryByEventAndEndpointParams struct {
	EventID    pgtype.UUID `json:"event_id"`
	EndpointID pgtype.UUID `json:"endpoint_id"`
}

// GetDeliveryByEventAndEndpoint
//
//	SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries
//	WHERE event_id = $1 AND endpoint_id = $2
//	LIMIT 1
func (q *Queries) GetDeliveryByEventAndEndpoint(ctx context.Context, arg GetDeliveryByEventAndEndpointParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByEventAndEndpoint, arg.EventID, arg.EndpointID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptNumber,
		&i.NextAttemptAt,
		&i.LastHttpStatus,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries WHERE id = $1 LIMIT 1
`

// GetDeliveryByID
//
//	SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries WHERE id = $1 LIMIT 1
func (q *Queries) GetDeliveryByID(ctx context.Context, id pgtype.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByID, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptNumber,
		&i.NextAttemptAt,
		&i.LastHttpStatus,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryWithDetails = `-- name: GetDeliveryWithDetails :one
SELECT
    d.id, d.attempt_number, d.status,
    e.id AS event_id, e.payload, e.event_type,
    ep.id AS endpoint_id, ep.url, ep.secret,
    ep.timeout_ms, ep.is_active, ep.rate_limit_rps
FROM deliveries d
JOIN events e    ON e.id  = d.event_id
JOIN endpoints ep ON ep.id = d.endpoint_id
WHERE d.id = $1
LIMIT 1
`

type GetDeliveryWithDetailsRow struct {
	ID            pgtype.UUID    `json:"id"`
	AttemptNumber int32          `json:"attempt_number"`
	Status        DeliveryStatus `json:"status"`
	EventID       pgtype.UUID    `json:"event_id"`
	Payload       []byte         `json:"payload"`
	EventType     string         `json:"event_type"`
	EndpointID    pgtype.UUID    `json:"endpoint_id"`
	Url           string         `json:"url"`
	Secret        string         `json:"secret"`
	TimeoutMs     int32          `json:"timeout_ms"`
	IsActive      bool           `json:"is_active"`
	RateLimitRps  int32          `json:"rate_limit_rps"`
}

// GetDeliveryWithDetails
//
//	SELECT
//	    d.id, d.attempt_number, d.status,
//	    e.id AS event_id, e.payload, e.event_type,
//	    ep.id AS endpoint_id, ep.url, ep.secret,
//	    ep.timeout_ms, ep.is_active, ep.rate_limit_rps
//	FROM deliveries d
//	JOIN events e    ON e.id  = d.event_id
//	JOIN endpoints ep ON ep.id = d.endpoint_id
//	WHERE d.id = $1
//	LIMIT 1
func (q *Queries) GetDeliveryWithDetails(ctx context.Context, id pgtype.UUID) (GetDeliveryWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getDeliveryWithDetails, id)
	var i GetDeliveryWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.AttemptNumber,
		&i.Status,
		&i.EventID,
		&i.Payload,
		&i.EventType,
		&i.EndpointID,
		&i.Url,
		&i.Secret,
		&i.TimeoutMs,
		&i.IsActive,
		&i.RateLimitRps,
	)
	return i, err
}

const listDeadLettered = `-- name: ListDeadLettered :many
SELECT d.id, d.event_id, d.endpoint_id, d.status, d.attempt_number, d.next_attempt_at, d.last_http_status, d.last_response_body, d.last_error, d.delivered_at, d.created_at, d.updated_at, e.event_type, e.payload
FROM deliveries d
JOIN events e ON e.id = d.event_id
WHERE d.status = 'dead_lettered'
    AND e.project_id = $1
ORDER BY d.updated_at DESC
LIMIT $2
`

type ListDeadLetteredParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
}

type ListDeadLetteredRow struct {
	ID               pgtype.UUID        `json:"id"`
	EventID          pgtype.UUID        `json:"event_id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	Status           DeliveryStatus     `json:"status"`
	AttemptNumber    int32              `json:"attempt_number"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	LastHttpStatus   *int32             `json:"last_http_status"`
	LastResponseBody *string            `json:"last_response_body"`
	LastError        *string            `json:"last_error"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EventType        string             `json:"event_type"`
	Payload          []byte             `json:"payload"`
}

// ListDeadLettered
//
//	SELECT d.id, d.event_id, d.endpoint_id, d.status, d.attempt_number, d.next_attempt_at, d.last_http_status, d.last_response_body, d.last_error, d.delivered_at, d.created_at, d.updated_at, e.event_type, e.payload
//	FROM deliveries d
//	JOIN events e ON e.id = d.event_id
//	WHERE d.status = 'dead_lettered'
//	    AND e.project_id = $1
//	ORDER BY d.updated_at DESC
//	LIMIT $2
func (q *Queries) ListDeadLettered(ctx context.Context, arg ListDeadLetteredParams) ([]ListDeadLetteredRow, error) {
	rows, err := q.db.Query(ctx, listDeadLettered, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeadLetteredRow
	for rows.Next() {
		var i ListDeadLetteredRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptNumber,
			&i.NextAttemptAt,
			&i.LastHttpStatus,
			&i.LastResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByEndpoint = `-- name: ListDeliveriesByEndpoint :many
SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries
WHERE endpoint_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListDeliveriesByEndpointParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	Limit      int32       `json:"limit"`
}

// ListDeliveriesByEndpoint
//
//	SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries
//	WHERE endpoint_id = $1
//	ORDER BY created_at DESC
//	LIMIT $2
func (q *Queries) ListDeliveriesByEndpoint(ctx context.Context, arg ListDeliveriesByEndpointParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByEndpoint, arg.EndpointID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptNumber,
			&i.NextAttemptAt,
			&i.LastHttpStatus,
			&i.LastResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByEvent = `-- name: ListDeliveriesByEvent :many
SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries
WHERE event_id = $1
ORDER BY created_at DESC
`

// ListDeliveriesByEvent
//
//	SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries
//	WHERE event_id = $1
//	ORDER BY created_at DESC
func (q *Queries) ListDeliveriesByEvent(ctx context.Context, eventID pgtype.UUID) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptNumber,
			&i.NextAttemptAt,
			&i.LastHttpStatus,
			&i.LastResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueRetries = `-- name: ListDueRetries :many
SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries
WHERE status = 'pending'
    AND next_attempt_at <= NOW()
ORDER BY next_attempt_at ASC
LIMIT $1
`

// ListDueRetries
//
//	SELECT id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at FROM deliveries
//	WHERE status = 'pending'
//	    AND next_attempt_at <= NOW()
//	ORDER BY next_attempt_at ASC
//	LIMIT $1
func (q *Queries) ListDueRetries(ctx context.Context, limit int32) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDueRetries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptNumber,
			&i.NextAttemptAt,
			&i.LastHttpStatus,
			&i.LastResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDelivery = `-- name: ResetDelivery :one
UPDATE deliveries
SET
    status             = 'pending',
    attempt_number     = 0,
    next_attempt_at    = NOW(),
    last_http_status   = NULL,
    last_response_body = NULL,
    last_error         = NULL,
    delivered_at       = NULL,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
`

// ResetDelivery
//
//	UPDATE deliveries
//	SET
//	    status             = 'pending',
//	    attempt_number     = 0,
//	    next_attempt_at    = NOW(),
//	    last_http_status   = NULL,
//	    last_response_body = NULL,
//	    last_error         = NULL,
//	    delivered_at       = NULL,
//	    updated_at         = NOW()
//	WHERE id = $1
//	RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
func (q *Queries) ResetDelivery(ctx context.Context, id pgtype.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, resetDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptNumber,
		&i.NextAttemptAt,
		&i.LastHttpStatus,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveryFailed = `-- name: UpdateDeliveryFailed :one
UPDATE deliveries
SET
    status              = $2,
    attempt_number      = attempt_number + 1,
    last_http_status    = $3,
    last_response_body  = $4,
    last_error          = $5,
    next_attempt_at     = $6,
    updated_at          = NOW()
WHERE id = $1
RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
`

type UpdateDeliveryFailedParams struct {
	ID               pgtype.UUID        `json:"id"`
	Status           DeliveryStatus     `json:"status"`
	LastHttpStatus   *int32             `json:"last_http_status"`
	LastResponseBody *string            `json:"last_response_body"`
	LastError        *string            `json:"last_error"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
}

// UpdateDeliveryFailed
//
//	UPDATE deliveries
//	SET
//	    status              = $2,
//	    attempt_number      = attempt_number + 1,
//	    last_http_status    = $3,
//	    last_response_body  = $4,
//	    last_error          = $5,
//	    next_attempt_at     = $6,
//	    updated_at          = NOW()
//	WHERE id = $1
//	RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
func (q *Queries) UpdateDeliveryFailed(ctx context.Context, arg UpdateDeliveryFailedParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryFailed,
		arg.ID,
		arg.Status,
		arg.LastHttpStatus,
		arg.LastResponseBody,
		arg.LastError,
		arg.NextAttemptAt,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptNumber,
		&i.NextAttemptAt,
		&i.LastHttpStatus,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveryInFlight = `-- name: UpdateDeliveryInFlight :one
UPDATE deliveries
SET status = 'in_flight', updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
`

// UpdateDeliveryInFlight
//
//	UPDATE deliveries
//	SET status = 'in_flight', updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
func (q *Queries) UpdateDeliveryInFlight(ctx context.Context, id pgtype.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryInFlight, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptNumber,
		&i.NextAttemptAt,
		&i.LastHttpStatus,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliverySuccess = `-- name: UpdateDeliverySuccess :one
UPDATE deliveries
SET
    status           = 'delivered',
    attempt_number   = attempt_number + 1,
    last_http_status = $2,
    delivered_at     = NOW(),
    updated_at       = NOW()
WHERE id = $1
RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
`

type UpdateDeliverySuccessParams struct {
	ID             pgtype.UUID `json:"id"`
	LastHttpStatus *int32      `json:"last_http_status"`
}

// UpdateDeliverySuccess
//
//	UPDATE deliveries
//	SET
//	    status           = 'delivered',
//	    attempt_number   = attempt_number + 1,
//	    last_http_status = $2,
//	    delivered_at     = NOW(),
//	    updated_at       = NOW()
//	WHERE id = $1
//	RETURNING id, event_id, endpoint_id, status, attempt_number, next_attempt_at, last_http_status, last_response_body, last_error, delivered_at, created_at, updated_at
func (q *Queries) UpdateDeliverySuccess(ctx context.Context, arg UpdateDeliverySuccessParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliverySuccess, arg.ID, arg.LastHttpStatus)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptNumber,
		&i.NextAttemptAt,
		&i.LastHttpStatus,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
