// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_attempt.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO delivery_attempts (delivery_id, attempt_number, http_status, response_body, error)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, delivery_id, attempt_number, http_status, response_body, error, attempted_at
`

type CreateDeliveryAttemptParams struct {
	DeliveryID    pgtype.UUID `json:"delivery_id"`
	AttemptNumber int32       `json:"attempt_number"`
	HttpStatus    *int32      `json:"http_status"`
	ResponseBody  *string     `json:"response_body"`
	Error         *string     `json:"error"`
}

// CreateDeliveryAttempt
//
//	INSERT INTO delivery_attempts (delivery_id, attempt_number, http_status, response_body, error)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, delivery_id, attempt_number, http_status, response_body, error, attempted_at
func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt,
		arg.DeliveryID,
		arg.AttemptNumber,
		arg.HttpStatus,
		arg.ResponseBody,
		arg.Error,
	)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.AttemptNumber,
		&i.HttpStatus,
		&i.ResponseBody,
		&i.Error,
		&i.AttemptedAt,
	)
	return i, err
}

const listAttemptsByDelivery = `-- name: ListAttemptsByDelivery :many
SELECT id, delivery_id, attempt_number, http_status, response_body, error, attempted_at FROM delivery_attempts
WHERE delivery_id = $1
ORDER BY attempted_at ASC
`

// ListAttemptsByDelivery
//
//	SELECT id, delivery_id, attempt_number, http_status, response_body, error, attempted_at FROM delivery_attempts
//	WHERE delivery_id = $1
//	ORDER BY attempted_at ASC
func (q *Queries) ListAttemptsByDelivery(ctx context.Context, deliveryID pgtype.UUID) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByDelivery, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.AttemptNumber,
			&i.HttpStatus,
			&i.ResponseBody,
			&i.Error,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
