// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (project_id, url, description, secret, rate_limit_rps, timeout_ms)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at
`

type CreateEndpointParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	Url          string      `json:"url"`
	Description  *string     `json:"description"`
	Secret       string      `json:"secret"`
	RateLimitRps int32       `json:"rate_limit_rps"`
	TimeoutMs    int32       `json:"timeout_ms"`
}

// CreateEndpoint
//
//	INSERT INTO endpoints (project_id, url, description, secret, rate_limit_rps, timeout_ms)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	RETURNING id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at
func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.ProjectID,
		arg.Url,
		arg.Description,
		arg.Secret,
		arg.RateLimitRps,
		arg.TimeoutMs,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.IsActive,
		&i.RateLimitRps,
		&i.TimeoutMs,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints
WHERE id = $1 AND project_id = $2
`

type DeleteEndpointParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// DeleteEndpoint
//
//	DELETE FROM endpoints
//	WHERE id = $1 AND project_id = $2
func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, arg.ID, arg.ProjectID)
	return err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at FROM endpoints
WHERE id = $1 AND project_id = $2
LIMIT 1
`

type GetEndpointByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// GetEndpointByID
//
//	SELECT id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at FROM endpoints
//	WHERE id = $1 AND project_id = $2
//	LIMIT 1
func (q *Queries) GetEndpointByID(ctx context.Context, arg GetEndpointByIDParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, arg.ID, arg.ProjectID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.IsActive,
		&i.RateLimitRps,
		&i.TimeoutMs,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveEndpointsByProject = `-- name: ListActiveEndpointsByProject :many
SELECT id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at FROM endpoints
WHERE project_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

// ListActiveEndpointsByProject
//
//	SELECT id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at FROM endpoints
//	WHERE project_id = $1 AND is_active = TRUE
//	ORDER BY created_at DESC
func (q *Queries) ListActiveEndpointsByProject(ctx context.Context, projectID pgtype.UUID) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listActiveEndpointsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Description,
			&i.Secret,
			&i.IsActive,
			&i.RateLimitRps,
			&i.TimeoutMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointsByProject = `-- name: ListEndpointsByProject :many
SELECT id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at FROM endpoints
WHERE project_id = $1
ORDER BY created_at DESC
`

// ListEndpointsByProject
//
//	SELECT id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at FROM endpoints
//	WHERE project_id = $1
//	ORDER BY created_at DESC
func (q *Queries) ListEndpointsByProject(ctx context.Context, projectID pgtype.UUID) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Description,
			&i.Secret,
			&i.IsActive,
			&i.RateLimitRps,
			&i.TimeoutMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET
    url            = COALESCE($3, url),
    description    = COALESCE($4, description),
    is_active      = COALESCE($5, is_active),
    rate_limit_rps = COALESCE($6, rate_limit_rps),
    timeout_ms     = COALESCE($7, timeout_ms)
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at
`

type UpdateEndpointParams struct {
	ID           pgtype.UUID `json:"id"`
	ProjectID    pgtype.UUID `json:"project_id"`
	Url          *string     `json:"url"`
	Description  *string     `json:"description"`
	IsActive     *bool       `json:"is_active"`
	RateLimitRps *int32      `json:"rate_limit_rps"`
	TimeoutMs    *int32      `json:"timeout_ms"`
}

// UpdateEndpoint
//
//	UPDATE endpoints
//	SET
//	    url            = COALESCE($3, url),
//	    description    = COALESCE($4, description),
//	    is_active      = COALESCE($5, is_active),
//	    rate_limit_rps = COALESCE($6, rate_limit_rps),
//	    timeout_ms     = COALESCE($7, timeout_ms)
//	WHERE id = $1 AND project_id = $2
//	RETURNING id, project_id, url, description, secret, is_active, rate_limit_rps, timeout_ms, created_at
func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.ID,
		arg.ProjectID,
		arg.Url,
		arg.Description,
		arg.IsActive,
		arg.RateLimitRps,
		arg.TimeoutMs,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.IsActive,
		&i.RateLimitRps,
		&i.TimeoutMs,
		&i.CreatedAt,
	)
	return i, err
}
