// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (project_id, idempotency_key, event_type, payload, headers)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, idempotency_key, event_type, payload, headers, ingested_at
`

type CreateEventParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
	EventType      string      `json:"event_type"`
	Payload        []byte      `json:"payload"`
	Headers        []byte      `json:"headers"`
}

// CreateEvent
//
//	INSERT INTO events (project_id, idempotency_key, event_type, payload, headers)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, project_id, idempotency_key, event_type, payload, headers, ingested_at
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.EventType,
		arg.Payload,
		arg.Headers,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.EventType,
		&i.Payload,
		&i.Headers,
		&i.IngestedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, project_id, idempotency_key, event_type, payload, headers, ingested_at FROM events
WHERE id = $1 AND project_id = $2
LIMIT 1
`

type GetEventByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// GetEventByID
//
//	SELECT id, project_id, idempotency_key, event_type, payload, headers, ingested_at FROM events
//	WHERE id = $1 AND project_id = $2
//	LIMIT 1
func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.ID, arg.ProjectID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.EventType,
		&i.Payload,
		&i.Headers,
		&i.IngestedAt,
	)
	return i, err
}

const getEventByIdempotencyKey = `-- name: GetEventByIdempotencyKey :one
SELECT id, project_id, idempotency_key, event_type, payload, headers, ingested_at FROM events
WHERE project_id = $1 AND idempotency_key = $2
LIMIT 1
`

type GetEventByIdempotencyKeyParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

// GetEventByIdempotencyKey
//
//	SELECT id, project_id, idempotency_key, event_type, payload, headers, ingested_at FROM events
//	WHERE project_id = $1 AND idempotency_key = $2
//	LIMIT 1
func (q *Queries) GetEventByIdempotencyKey(ctx context.Context, arg GetEventByIdempotencyKeyParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.EventType,
		&i.Payload,
		&i.Headers,
		&i.IngestedAt,
	)
	return i, err
}

const listEventsByProject = `-- name: ListEventsByProject :many
SELECT id, project_id, idempotency_key, event_type, payload, headers, ingested_at FROM events
WHERE project_id = $1
    AND ($2::text = '' OR event_type = $2)
    AND ($3::uuid IS NULL OR id < $3)
ORDER BY ingested_at DESC
LIMIT $4
`

type ListEventsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   pgtype.UUID `json:"column_3"`
	Limit     int32       `json:"limit"`
}

// ListEventsByProject
//
//	SELECT id, project_id, idempotency_key, event_type, payload, headers, ingested_at FROM events
//	WHERE project_id = $1
//	    AND ($2::text = '' OR event_type = $2)
//	    AND ($3::uuid IS NULL OR id < $3)
//	ORDER BY ingested_at DESC
//	LIMIT $4
func (q *Queries) ListEventsByProject(ctx context.Context, arg ListEventsByProjectParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByProject,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IdempotencyKey,
			&i.EventType,
			&i.Payload,
			&i.Headers,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
