// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryStatus string

const (
	DeliveryStatusPending      DeliveryStatus = "pending"
	DeliveryStatusInFlight     DeliveryStatus = "in_flight"
	DeliveryStatusDelivered    DeliveryStatus = "delivered"
	DeliveryStatusFailed       DeliveryStatus = "failed"
	DeliveryStatusDeadLettered DeliveryStatus = "dead_lettered"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type Delivery struct {
	ID               pgtype.UUID        `json:"id"`
	EventID          pgtype.UUID        `json:"event_id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	Status           DeliveryStatus     `json:"status"`
	AttemptNumber    int32              `json:"attempt_number"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	LastHttpStatus   *int32             `json:"last_http_status"`
	LastResponseBody *string            `json:"last_response_body"`
	LastError        *string            `json:"last_error"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Endpoint struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Url          string             `json:"url"`
	Description  *string            `json:"description"`
	Secret       string             `json:"secret"`
	IsActive     bool               `json:"is_active"`
	RateLimitRps int32              `json:"rate_limit_rps"`
	TimeoutMs    int32              `json:"timeout_ms"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	IdempotencyKey *string            `json:"idempotency_key"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	Headers        []byte             `json:"headers"`
	IngestedAt     pgtype.Timestamptz `json:"ingested_at"`
}

type Project struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ApiKey    string             `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
