// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, api_key)
VALUES ($1, $2)
RETURNING id, name, api_key, created_at
`

type CreateProjectParams struct {
	Name   string `json:"name"`
	ApiKey string `json:"api_key"`
}

// CreateProject
//
//	INSERT INTO projects (name, api_key)
//	VALUES ($1, $2)
//	RETURNING id, name, api_key, created_at
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.ApiKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByAPIKey = `-- name: GetProjectByAPIKey :one
SELECT id, name, api_key, created_at FROM projects
WHERE api_key = $1
LIMIT 1
`

// GetProjectByAPIKey
//
//	SELECT id, name, api_key, created_at FROM projects
//	WHERE api_key = $1
//	LIMIT 1
func (q *Queries) GetProjectByAPIKey(ctx context.Context, apiKey string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByAPIKey, apiKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, api_key, created_at FROM projects
WHERE id = $1
LIMIT 1
`

// GetProjectByID
//
//	SELECT id, name, api_key, created_at FROM projects
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectAPIKey = `-- name: UpdateProjectAPIKey :one
UPDATE projects
SET api_key = $2
WHERE id = $1
RETURNING id, name, api_key, created_at
`

type UpdateProjectAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	ApiKey string      `json:"api_key"`
}

// UpdateProjectAPIKey
//
//	UPDATE projects
//	SET api_key = $2
//	WHERE id = $1
//	RETURNING id, name, api_key, created_at
func (q *Queries) UpdateProjectAPIKey(ctx context.Context, arg UpdateProjectAPIKeyParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectAPIKey, arg.ID, arg.ApiKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}
